// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThirdAPI.Models;

#nullable disable

namespace ThirdAPI.Migrations
{
    [DbContext(typeof(CompanyContext))]
    partial class CompanyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ThirdAPI.Models.Dept", b =>
                {
                    b.Property<int>("DeptNo")
                        .HasColumnType("int");

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DeptNo1")
                        .HasColumnType("int");

                    b.HasKey("DeptNo");

                    b.HasIndex("DeptNo1");

                    b.ToTable("Depts");
                });

            modelBuilder.Entity("ThirdAPI.Models.Emp", b =>
                {
                    b.Property<int>("Eno")
                        .HasColumnType("int");

                    b.Property<int?>("DeptNo")
                        .HasColumnType("int");

                    b.Property<string>("Ename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Eno");

                    b.HasIndex("DeptNo");

                    b.ToTable("Emps");
                });

            modelBuilder.Entity("ThirdAPI.Models.Dept", b =>
                {
                    b.HasOne("ThirdAPI.Models.Dept", null)
                        .WithMany("Depts")
                        .HasForeignKey("DeptNo1");
                });

            modelBuilder.Entity("ThirdAPI.Models.Emp", b =>
                {
                    b.HasOne("ThirdAPI.Models.Dept", "Deptno")
                        .WithMany()
                        .HasForeignKey("DeptNo");

                    b.Navigation("Deptno");
                });

            modelBuilder.Entity("ThirdAPI.Models.Dept", b =>
                {
                    b.Navigation("Depts");
                });
#pragma warning restore 612, 618
        }
    }
}
