// <auto-generated />
using System;
using ExampleProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExampleProject.Migrations.Movie
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExampleProject.Models.BookingDetails", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("Date");

                    b.Property<int?>("LoginUserId")
                        .HasColumnType("int");

                    b.Property<int?>("MovieDetailsMovieId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int?>("ScreenDetailsScreenId")
                        .HasColumnType("int");

                    b.Property<int>("ScreenId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("LoginUserId");

                    b.HasIndex("MovieDetailsMovieId");

                    b.HasIndex("ScreenDetailsScreenId");

                    b.ToTable("bookingDetails");
                });

            modelBuilder.Entity("ExampleProject.Models.Login", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("logins");
                });

            modelBuilder.Entity("ExampleProject.Models.MovieDetails", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("Date");

                    b.Property<string>("MovieLanguage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MovieName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ScreenDetailsScreenId")
                        .HasColumnType("int");

                    b.Property<int>("ScreenId")
                        .HasColumnType("int");

                    b.HasKey("MovieId");

                    b.HasIndex("ScreenDetailsScreenId");

                    b.ToTable("movieDetails");
                });

            modelBuilder.Entity("ExampleProject.Models.ScreenDetails", b =>
                {
                    b.Property<int>("ScreenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScreenId"));

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("SeatNo")
                        .HasColumnType("int");

                    b.Property<string>("SeatStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeatType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ShowTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ScreenId");

                    b.ToTable("screenDetails");
                });

            modelBuilder.Entity("ExampleProject.Models.BookingDetails", b =>
                {
                    b.HasOne("ExampleProject.Models.Login", null)
                        .WithMany("BookingDetails")
                        .HasForeignKey("LoginUserId");

                    b.HasOne("ExampleProject.Models.MovieDetails", null)
                        .WithMany("Bookings")
                        .HasForeignKey("MovieDetailsMovieId");

                    b.HasOne("ExampleProject.Models.ScreenDetails", null)
                        .WithMany("BookingDetails")
                        .HasForeignKey("ScreenDetailsScreenId");
                });

            modelBuilder.Entity("ExampleProject.Models.MovieDetails", b =>
                {
                    b.HasOne("ExampleProject.Models.ScreenDetails", null)
                        .WithMany("Movies")
                        .HasForeignKey("ScreenDetailsScreenId");
                });

            modelBuilder.Entity("ExampleProject.Models.Login", b =>
                {
                    b.Navigation("BookingDetails");
                });

            modelBuilder.Entity("ExampleProject.Models.MovieDetails", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("ExampleProject.Models.ScreenDetails", b =>
                {
                    b.Navigation("BookingDetails");

                    b.Navigation("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
